{
    "comments": [],
    "consts": [],
    "events": [
        {
            "index": 0,
            "type": "onClickBegin",
            "x": 406.0,
            "y": 561.0
        }
    ],
    "forks": [],
    "functions": [
        {
            "function": "SceneManager_EndGame",
            "index": 1,
            "input": [],
            "x": 805.0,
            "y": 456.0
        }
    ],
    "nodeCount": 2,
    "onClickBegin": 1,
    "serializedValues": []
}