#pragma once

#include <unordered_map>
#include <string>
#include <vector>
#include "Scripting/Variable.h"



#define ECSfunc_Version 1.0
//Creation time : Mon Apr 10 03:08:34 2023


typedef Scripting::Variable(*CallableFunction)(std::vector<Scripting::Variable> const&);

class FunctionManager{
public: 
	static void CreateFunctionMap(std::unordered_map<std::string, CallableFunction>& map);
};



Scripting::Variable Animation_ChangeAnimationPath(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_AdvanceFrame(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_AdvanceAnimation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_SetFrame(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_SetAnimation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_GetFrame(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_GetAnimation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_SetAnimationLenght(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Animation_getAnimationLenght(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_getTextureWidth(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_getTextureHeight(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_setSrcRect(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_setFlipX(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_setFlipY(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_setRotaionPoint(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_scaledSize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Image_ChangeTexture(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetPlacement(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetPositioned(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetStreched(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_Move(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_MoveTo(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetSize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetSize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetTop(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetLeft(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetRight(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetBottom(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetTop(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetLeft(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetRight(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetBottom(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetAnchor(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchor(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchorCenter(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchorTopLeft(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchorTopRight(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchorBottomLeft(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetAnchorBottomRight(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetColor(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetColor(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_GetRenderScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetRenderScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_ResetRenderScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_SetInteractable(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Overlay_IsInteractable(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayImage_SetTexture(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayImage_GetTexture(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetFit(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetFit(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetVerticalAlignment(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetHorizontalAlignment(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetVerticalAlignment(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetHorizontalAlignment(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetFont(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetFont(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetText(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetText(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_GetPointSize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable OverlayText_SetPointSize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_setTrigger(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_isTrigger(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_setFriction(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_getFriction(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_setBounciness(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_getBounciness(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_setLinearVelocity(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicBody_getLinearVelocity(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetLocalPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetLocalScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetLocalPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetLocalPositionX(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetLocalPositionY(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetWorldPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetScaleX(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetScaleY(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetWorldScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetLocalRotation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetLocalRotation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_SetWorldRotation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetWorldPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetWorldScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_GetWorldRotation(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_Translate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_TranslateX(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_TranslateY(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_Rotate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Transform_Scale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable InputManager_keyDownEvent(std::vector<Scripting::Variable>const& vec);
Scripting::Variable InputManager_keyUpEvent(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicsManager_debugDraw(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicsManager_enableDebugDraw(std::vector<Scripting::Variable>const& vec);
Scripting::Variable PhysicsManager_handleBodies(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_SaveAll(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_Save(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_Load(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_SetSlot(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_GetSlot(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_Set(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_Get(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_ClearSlot(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_Exists(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SaveManager_DeleteSave(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SceneManager_ChangeScene(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SceneManager_ResetScene(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SceneManager_EndGame(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SceneManager_getNumberOfScenes(std::vector<Scripting::Variable>const& vec);
Scripting::Variable SceneManager_GetCurrentScenePath(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Entity(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_EntityName(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Script(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Print(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Add(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Subtract(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Multiply(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Divide(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Power(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Math_Root(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_Equals(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_NotEquals(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_Lesser(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_Greater(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_LesserOrEqual(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_GreaterOrEqual(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_And(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_Or(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Logic_Negate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Create(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Magnitude(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_X(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Y(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Normalize(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Angle(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_AngleWithVector(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Rotate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Add(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Subtract(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Dot(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Cross(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Vector2D_Multiply(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Equals(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Concatenate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Substring(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Begining(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_End(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Trim(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_TrimBlanks(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_GetLetter(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_Find(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_ToString(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_String_LeadingZeros(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_Set(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_Get(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_SetLocal(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_GetLocal(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_SetGlobal(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Attribute_GetGlobal(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Now(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_WeekDay(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_ShortWeekDay(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Month(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_ShortMonth(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_DayOfWeekIndex(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_MonthIndex(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_MonthDay(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Year(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Hours(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Minutes(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Seconds(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_Since(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_TimeHHMM(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_TimeHHMMSS(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_TimeStamp(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Time_DDMMYY(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Camera_GetPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Camera_SetPosition(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Camera_GetScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Camera_SetScale(std::vector<Scripting::Variable>const& vec);
Scripting::Variable ScriptFunctionality_Open_URL(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Time_GetTimeSinceBegining(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Time_GetTimeSinceBeginingMilliseconds(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Time_GetDeltaTime(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Time_GetFrameRate(std::vector<Scripting::Variable>const& vec);
Scripting::Variable Time_GetPhysicsDeltaTime(std::vector<Scripting::Variable>const& vec);
